language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1

before_script:
  - "cp spec/config/database.example.yml spec/config/database.yml"
  - "bundle exec rake spec:db:setup"

script: bundle exec rake spec

branches:
  only:
    - master
